spring:
  application:
    name: tasktracker
  datasource:
    url: jdbc:h2:mem:DEFAULT
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
